apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fractal-faas-images
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/images:1.0.0
          ports:
            - containerPort: 8081
          env:
            - name: TARGET
              value: "Spring Boot Sample v1"
