image-service-url: ${IMAGE_SERVICE_URL:http://fractal-faas-images.default.127.0.0.1.sslip.io/computePng}
#mandelbrot-service-url: ${MANDELBROT_SERVICE_URL:http://fractal-faas-mandelbrot.default.127.0.0.1.sslip.io/mandelbrotQuad}
mandelbrot-service-url: ${MANDELBROT_SERVICE_URL:http://127.0.0.1:8080/mandelbrotQuad}
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: false
  enable-native-support: true
server:
  port: 8080

spring:
  cloud:
    function:
      web:
#        path: /functions
  codec:
    max-in-memory-size: 10MB

