apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fractal-faas-mandelbrot
spec:
  template:
    spec:
      containers:
        - image: europe-west3-docker.pkg.dev/fractal-functions/images/mandelbrot:latest
          resources:
            limits:
              memory: 1000Mi
          ports:
            - containerPort: 8080
          env:
            - name: IMAGE_SERVICE_URL
              value: "https://fractal-faas-images-caskxmpsyq-ey.a.run.app/computePng"

              #value: "http://fractal-faas-images.default.127.0.0.1.sslip.io/computePng"
              #fractal-faas-images.default.cluster.local
