apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fractal-faas-mandelbrot
spec:
  template:
    spec:
      containers:
        - image: dev.local/mandelbrot:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: IMAGE_SERVICE_URL
              value: "http://fractal-faas-images.default.svc.cluster.local"

              #value: "http://fractal-faas-images.default.127.0.0.1.sslip.io/computePng"
              #fractal-faas-images.default.cluster.local
